fix bug

diff --git a/.github/workflows/example.yml b/.github/workflows/example.yml
--- a/.github/workflows/example.yml
+++ b/.github/workflows/example.yml
@@ -3,31 +3,34 @@ name: github-actions-example
 on: push
 
 jobs:
-  job-one:
+  example:
     runs-on: ubuntu-latest
     steps:
-      - run: exit 1
+      - id: step-one
+        run: echo "run step one"
+ 
+      - id: step-two
+        run: |
+          echo " run step two"
+          exit 1
 
-  job-two:
-    needs: job-one
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo "Function success()"
+      - id: step-three
+        run: |
+          echo "run step three"
+          echo "function success()"
 
-  job-three:
-    needs: [job-one, job-two]
-    if: ${{ failure() }}
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo "Function failure()"
+      - id: step-four
+        if: ${{ failure() }}
+        run: |
+          echo "run step four"
+          echo "function failure()"
 
-  job-four:
-    needs: [job-one, job-two, job-three]
-    if: ${{ always() }}
-    runs-on: ubuntu-latest
-    steps:
-      - run: |
-          echo "Function always()"
-          echo "Result job-one: ${{ needs.job-one.result }}"
-          echo "Result job-two: ${{ needs.job-two.result }}"
-          echo "Result job-three: ${{ needs.job-three.result }}"
+      - id: step-five
+        if: ${{ always() }}
+        run: |
+          echo "run step five"
+          echo "function always()"
+          echo "outcome step one: ${{ steps.step-one.outcome }}"
+          echo "outcome step two: ${{ steps.step-two.outcome }}"
+          echo "outcome step three: ${{ steps.step-three.outcome }}"
+          echo "outcome step four: ${{ steps.step-four.outcome }}"
